"""empty message

Revision ID: 98097d9d844a
Revises: ba6891d9d199
Create Date: 2020-09-06 22:53:23.769600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98097d9d844a'
down_revision = 'ba6891d9d199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('url', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'url')
    # ### end Alembic commands ###
