"""empty message

Revision ID: b0df64acd9aa
Revises: 
Create Date: 2018-09-11 08:43:23.937981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0df64acd9aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmbaid', sa.Integer(), nullable=True),
    sa.Column('title', sa.Unicode(length=16), nullable=True),
    sa.Column('first_name', sa.Unicode(length=128), nullable=True),
    sa.Column('last_name', sa.Unicode(length=128), nullable=True),
    sa.Column('organisation', sa.Unicode(length=128), nullable=True),
    sa.Column('position', sa.Unicode(length=128), nullable=True),
    sa.Column('country', sa.Unicode(length=128), nullable=True),
    sa.Column('biography', sa.UnicodeText(), nullable=True),
    sa.Column('contact_email', sa.Unicode(length=255), nullable=True),
    sa.Column('personal_url', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('range',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmbaid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('countries', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('citation', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('resources_people',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources_people')
    op.drop_table('resource')
    op.drop_table('range')
    op.drop_table('person')
    # ### end Alembic commands ###
