"""empty message

Revision ID: ba6891d9d199
Revises:
Create Date: 2020-08-21 11:43:17.660971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6891d9d199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('department', sa.Unicode(length=255), nullable=True),
    sa.Column('building', sa.UnicodeText(), nullable=True),
    sa.Column('street', sa.UnicodeText(), nullable=True),
    sa.Column('postcode', sa.Unicode(length=16), nullable=True),
    sa.Column('city', sa.Unicode(length=255), nullable=True),
    sa.Column('country', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcid', sa.Unicode(length=128), nullable=True),
    sa.Column('source_id', sa.Unicode(length=64), nullable=True),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.Column('first_name', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(length=128), nullable=True),
    sa.Column('gender', sa.Unicode(length=64), nullable=True),
    sa.Column('position', sa.UnicodeText(), nullable=True),
    sa.Column('contact_email', sa.Unicode(length=255), nullable=True),
    sa.Column('personal_urls', sa.UnicodeText(), nullable=True),
    sa.Column('select_career_stage', sa.Unicode(length=64), nullable=True),
    sa.Column('career_stage_note', sa.Unicode(length=255), nullable=True),
    sa.Column('ecr_list', sa.Boolean(), nullable=True),
    sa.Column('official_functions', sa.UnicodeText(), nullable=True),
    sa.Column('upload_photo', sa.String(length=512), nullable=True),
    sa.Column('allow_public', sa.Boolean(), nullable=True),
    sa.Column('allow_photo', sa.Boolean(), nullable=True),
    sa.Column('allow_contact', sa.Boolean(), nullable=True),
    sa.Column('allow_registry', sa.Boolean(), nullable=True),
    sa.Column('allow_newsletter', sa.Boolean(), nullable=True),
    sa.Column('_indexer', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcid'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('acronym', sa.Unicode(length=16), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('funding', sa.UnicodeText(), nullable=True),
    sa.Column('investigators', sa.UnicodeText(), nullable=True),
    sa.Column('homepage', sa.UnicodeText(), nullable=True),
    sa.Column('location', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=2048), nullable=True),
    sa.Column('url', sa.Unicode(length=2048), nullable=True),
    sa.Column('citation', sa.UnicodeText(), nullable=True),
    sa.Column('abstract', sa.UnicodeText(), nullable=True),
    sa.Column('resource_type', sa.Enum('HOMEPAGE', 'RESUME', 'PROFILE', 'BOOK', 'PAPER', 'ARTICLE', name='resourcetype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation_people',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], )
    )
    op.create_table('projects_people',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )
    op.create_table('resources_people',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], )
    )
    op.create_table('expertise_people',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('expertise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertise.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expertise_people')
    op.drop_table('resources_people')
    op.drop_table('projects_people')
    op.drop_table('organisation_people')
    op.drop_table('expertise')
    op.drop_table('topic')
    op.drop_table('resource')
    op.drop_table('project')
    op.drop_table('person')
    op.drop_table('organisation')
    # ### end Alembic commands ###
