# Generated by Django 3.1.2 on 2020-11-03 20:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('post_code', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Expertise',
                'verbose_name_plural': 'Expertise',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('acronym', models.CharField(max_length=16)),
                ('date_start', models.DateField()),
                ('date_ending', models.DateField()),
                ('funding', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('homepage', models.URLField()),
                ('location', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('position', models.CharField(max_length=256)),
                ('contact_email', models.CharField(max_length=256)),
                ('career_stage', models.CharField(choices=[('UNDERGRAD', 'Undergraduate student (e.g. BSc/BA)'), ('POSTGRAD', 'Postgraduate student (Masters/PhD student)'), ('POSTDOC', 'Postdoc/Junior Researcher'), ('ACADEMIC', 'Academic (Senior Researcher, Professor)'), ('PUBLICSECTOR', 'Practitioner in the public/government sector'), ('PRIVATESECTOR', 'Practitioner or business in the private sector'), ('OTHER', 'Other (short text)')], max_length=16)),
                ('career_stage_note', models.CharField(max_length=256, verbose_name='Other')),
                ('career_graduation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Year of last degree graduation')),
                ('preferences', multiselectfield.db.fields.MultiSelectField(choices=[('join_ecr', 'Would you like to join the MRI Early Career Researchers (ECRs) fellows group? (applies to currently enrolled students, practitioners, or postgraduate/postdoctoral scholars up to 5 years since obtaining last degree)'), ('contact_me', 'I allow MRI to contact me regarding my profile, as listed on the database, to link to and promote in its communications channels (website, social media, newsletter article).'), ('expert_registry', 'I would like to be added to an experts registry for internal use by the MRI Coordination Office to identify and connect with external requests for consultancies, expertise, provide inputs for policy briefs/policy reviews, speaking role, or interviews (such as by third parties, journalists or collaborators of the MRI).'), ('newsletter', 'I would like to receive monthly MRI Global Newsletters and Newsflashes from the MRI')], max_length=46)),
                ('official_functions', models.TextField(help_text='Official functions that I hold in national and international programs, commissions, etc.')),
                ('upload_photo', models.FileField(upload_to='')),
                ('url_personal', models.URLField(help_text='Link to personal or professional homepage', verbose_name='Personal website')),
                ('url_cv', models.URLField(help_text='Link to CV, e.g. on LinkedIn', verbose_name='Curriculum Vitae')),
                ('url_researchgate', models.URLField(help_text='Link to your profile', verbose_name='ResearchGate link')),
                ('orcid', models.CharField(help_text='ORCID is a persistent unique digital identifier that you own and control', max_length=128, unique=True, verbose_name='ORCID')),
                ('url_publications', models.URLField(verbose_name='Link to publications')),
                ('list_publications', models.TextField(verbose_name='Free text list of publications')),
                ('allow_public', models.BooleanField(help_text='I allow publishing my profile on the web')),
                ('allow_photo', models.BooleanField(help_text='I allow publishing my photo on the web')),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.affiliation')),
                ('disciplines', models.ManyToManyField(help_text='Disciplinary expertise topics', related_name='experts', to='people.Topic')),
                ('expertise', models.ManyToManyField(help_text='Research expertise', related_name='experts', to='people.Expertise')),
                ('projects', models.ManyToManyField(related_name='experts', to='people.Project')),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
            },
        ),
        migrations.AddField(
            model_name='expertise',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.topic'),
        ),
    ]
