# Generated by Django 3.1.3 on 2020-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='department',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('name', 'department')},
        ),
    ]
