# Generated by Django 3.1.3 on 2020-11-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201109_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload_photo',
            field=models.ImageField(blank=True, null=True, upload_to='people'),
        ),
    ]
