# Generated by Django 3.1.3 on 2020-11-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201109_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='disciplines',
        ),
        migrations.AlterField(
            model_name='person',
            name='upload_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/people'),
        ),
    ]
