# Generated by Django 3.1.3 on 2020-11-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20201117_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
