# Generated by Django 3.1.4 on 2021-01-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('expert_management', '0002_auto_20210126_0640'), ('expert_management', '0003_auto_20210126_0707')]

    dependencies = [
        ('expert_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='mpoly',
        ),
        migrations.AlterField(
            model_name='mountain',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_photo_public',
            field=models.BooleanField(default=False, verbose_name='I allow for my photo to be publicly visible in the MRI Expert Database'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='I allow for my profile to be publicly visible in the MRI Expert Database'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=False, verbose_name='I would like to subscribe to the MRI Global Newsletter'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='disciplinary_expertise',
            field=models.ManyToManyField(blank=True, to='expert_management.DisciplinaryExpertise'),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
