# Generated by Django 3.1.3 on 2020-12-15 12:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('expert_management', '0002_mountain'), ('expert_management', '0003_mountain_false'), ('expert_management', '0004_remove_mountain_false'), ('expert_management', '0005_expertise_mountain_ranges_of_research_interest'), ('expert_management', '0006_auto_20201215_1238'), ('expert_management', '0007_auto_20201215_1249')]

    dependencies = [
        ('expert_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=250)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='expertise',
            name='mountain_ranges_of_research_expertise',
            field=models.ManyToManyField(blank=True, related_name='_expertise_mountain_ranges_of_research_expertise_+', to='expert_management.Mountain'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_mountain_ranges_of_research_expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_mountain_ranges_of_research_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='mountain_ranges_of_research_interest',
            field=models.ManyToManyField(blank=True, related_name='_expertise_mountain_ranges_of_research_interest_+', to='expert_management.Mountain'),
        ),
    ]
