# Generated by Django 3.1.4 on 2021-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_management', '0002_auto_20210126_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
