# Generated by Django 3.1.4 on 2021-02-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_management', '0003_auto_20210129_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisciplinaryExpertise',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Format: .jpg, .png, Size: 300x350 pixels', null=True, upload_to='experts'),
        ),
    ]
