# Generated by Django 3.1.4 on 2021-02-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_management', '0004_auto_20210202_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atmosphericsciences',
            options={'verbose_name_plural': 'Atmospheric Sciences'},
        ),
        migrations.AlterModelOptions(
            name='biologicalsciences',
            options={'verbose_name_plural': 'Biological Sciences'},
        ),
        migrations.AlterModelOptions(
            name='cryosphericsciences',
            options={'verbose_name_plural': 'Cryospheric Sciences'},
        ),
        migrations.AlterModelOptions(
            name='earthsciences',
            options={'verbose_name_plural': 'Earth Sciences'},
        ),
        migrations.AlterModelOptions(
            name='geomountainsregistry',
            options={'verbose_name': 'Geo Mountains Registry', 'verbose_name_plural': 'Geo Mountains Registry'},
        ),
        migrations.AlterModelOptions(
            name='hydrosphericsciences',
            options={'verbose_name_plural': 'Hydrospheric Sciences'},
        ),
        migrations.AlterModelOptions(
            name='inputsorparticipationtounconventions',
            options={'verbose_name_plural': 'Inputs / Participation To UN Conventions'},
        ),
        migrations.AlterModelOptions(
            name='integratedsystems',
            options={'verbose_name_plural': 'Integrated Systems'},
        ),
        migrations.AlterModelOptions(
            name='methods',
            options={'verbose_name_plural': 'Methods'},
        ),
        migrations.AlterModelOptions(
            name='participationinassessments',
            options={'verbose_name_plural': 'Participation In Assessments'},
        ),
        migrations.AlterModelOptions(
            name='researchexpertise',
            options={'verbose_name_plural': 'Research Expertise'},
        ),
        migrations.AlterModelOptions(
            name='roleandinvolvement',
            options={'verbose_name': 'Roles and Involvement', 'verbose_name_plural': 'Roles and Involvement'},
        ),
        migrations.AlterModelOptions(
            name='socialsciencesandhumanities',
            options={'verbose_name_plural': 'Social Sciences And Humanities'},
        ),
        migrations.AlterModelOptions(
            name='spatialscaleofexpertise',
            options={'verbose_name_plural': 'Spatial Scale Of Expertise'},
        ),
        migrations.AlterModelOptions(
            name='statisticalfocus',
            options={'verbose_name_plural': 'Statistical Focus'},
        ),
        migrations.AlterModelOptions(
            name='timescales',
            options={'verbose_name_plural': 'Time Scales'},
        ),
        migrations.AlterField(
            model_name='expertise',
            name='inputs_or_participation_to_un_conventions',
            field=models.ManyToManyField(blank=True, to='expert_management.InputsOrParticipationToUNConventions', verbose_name='Inputs / Participation to UN Conventions'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='other_inputs_or_participation_to_un_conventions',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True, verbose_name='Other Inputs / Participation to UN Conventions'),
        ),
    ]
