# Generated by Django 3.1.6 on 2021-02-04 13:29

from django.db import migrations, models
import expert_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_management', '0005_auto_20210203_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='other_expertise',
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_atmospheric_sciences',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_biological_sciences',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_cryospheric_sciences',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_earth_sciences',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_hydrospheric_sciences',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_integrated_systems',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='other_social_sciences_and_humanities',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='inputs_or_participation_to_un_conventions',
            field=models.ManyToManyField(blank=True, to='expert_management.InputsOrParticipationToUNConventions', verbose_name='Inputs / Participation to United Nations Conventions'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='other_inputs_or_participation_to_un_conventions',
            field=models.CharField(blank=True, help_text='This should be a comma seperated list', max_length=1024, null=True, verbose_name='Other Inputs / Participation to United Nations Conventions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=expert_management.models.MultiSelectField(base_field=models.CharField(choices=[('join_ecr', 'I would like to join the MRI Early Career Researchers (ECRs) fellows group (for enrolled students, practitioners, or scholars within 5 years of obtaining last degree)'), ('contact_me', 'I allow the MRI to contact me about my profile and link to it in its communications channels (website, social media, newsletter article).'), ('expert_registry', 'I would like to be added to an experts registry for the MRI to connect me with external requests for consultancies, expertise, policy inputs, speaking roles, or interviews.')], max_length=128), blank=True, default=list, null=True, size=None),
        ),
    ]
