# Generated by Django 3.1.6 on 2021-03-09 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert_management', '0007_spamfilterword'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
